import RiemannHypothesisProofFactory.SubpowerDyadicEnergy.EventualDyadicBalance

#print axioms RiemannHypothesisProofFactory.SubpowerDyadicEnergy.dyadic_global_energy_balance
#print axioms RiemannHypothesisProofFactory.SubpowerDyadicEnergy.eventualDyadicDefectFrom_implies_sharp_power_energy_bound
#print axioms RiemannHypothesisProofFactory.SubpowerDyadicEnergy.eventualDyadicDefectFrom_implies_cumulative_energy_cubic_bound
