import RiemannHypothesisProofFactory.SubpowerDyadicEnergy.DiscreteKernel

#print axioms RiemannHypothesisProofFactory.SubpowerDyadicEnergy.prefix_square_identity
#print axioms RiemannHypothesisProofFactory.SubpowerDyadicEnergy.paperP1_implies_sharp_recursion
#print axioms RiemannHypothesisProofFactory.SubpowerDyadicEnergy.paperP1_implies_binary_recurrence
#print axioms RiemannHypothesisProofFactory.SubpowerDyadicEnergy.paperP1_implies_cubic_bound
