import RiemannHypothesisProofFactory.SelbergConditioning.PrimeFactorConstruction
import RiemannHypothesisProofFactory.SelbergConditioning.ConditioningWitness
import RiemannHypothesisProofFactory.SelbergConditioning.SelbergStability

open RiemannHypothesisProofFactory.SelbergConditioning

#print axioms centeredPrimeCoefficient_weighted_sum_zero
#print axioms primeFactorResidual_abs_le_log
#print axioms finite_prime_factor_conditioning_construction
#print axioms finite_two_sign_conditioning_obstruction
#print axioms finite_selberg_feedback_stability
