import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Tactic

open scoped BigOperators

namespace RiemannHypothesisProofFactory.SelbergConditioning

/-- The exact divisor-feedback residual generated by coefficients on primes. -/
noncomputable def primeFactorResidual (c : ℕ → ℝ) (n : ℕ) : ℝ :=
  ∑ p ∈ n.factorization.support, (n.factorization p : ℝ) * c p

/-- A finite coefficient family centered by correcting one distinguished prime. -/
noncomputable def centeredPrimeCoefficient
    (P : Finset ℕ) (q : ℕ) (raw : ℕ → ℝ) (p : ℕ) : ℝ :=
  if p ∉ P then 0
  else if p = q then
    -((q : ℝ) - 1) * ∑ r ∈ P.erase q, raw r / ((r : ℝ) - 1)
  else raw p

theorem centeredPrimeCoefficient_eq_raw
    (P : Finset ℕ) (q : ℕ) (raw : ℕ → ℝ) {p : ℕ}
    (hpP : p ∈ P) (hp : p ≠ q) :
    centeredPrimeCoefficient P q raw p = raw p := by
  simp [centeredPrimeCoefficient, hpP, hp]

theorem centeredPrimeCoefficient_eq_zero_of_not_mem
    (P : Finset ℕ) (q : ℕ) (raw : ℕ → ℝ) {p : ℕ} (hp : p ∉ P) :
    centeredPrimeCoefficient P q raw p = 0 := by
  simp [centeredPrimeCoefficient, hp]

/-- The correction at `q` makes the finite prime-power mean exactly zero. -/
theorem centeredPrimeCoefficient_weighted_sum_zero
    (P : Finset ℕ) (q : ℕ) (raw : ℕ → ℝ)
    (hqP : q ∈ P) (hq : 1 < q) :
    ∑ p ∈ P, centeredPrimeCoefficient P q raw p / ((p : ℝ) - 1) = 0 := by
  classical
  have hqne : (q : ℝ) - 1 ≠ 0 := by
    exact sub_ne_zero.mpr (by exact_mod_cast hq.ne')
  rw [← Finset.sum_erase_add _ _ hqP]
  have herase :
      ∑ p ∈ P.erase q,
          centeredPrimeCoefficient P q raw p / ((p : ℝ) - 1) =
        ∑ p ∈ P.erase q, raw p / ((p : ℝ) - 1) := by
    apply Finset.sum_congr rfl
    intro p hp
    rw [centeredPrimeCoefficient_eq_raw]
    · exact Finset.mem_of_mem_erase hp
    · exact (Finset.mem_erase.mp hp).1
  rw [herase]
  simp [centeredPrimeCoefficient, hqP]
  field_simp
  ring

/-- Prime-factor coefficients bounded by `C log p` generate a residual bounded by
`C log n`.  This is the exact finite arithmetic mechanism behind the manuscript's
divisor-feedback estimate. -/
theorem primeFactorResidual_abs_le_log
    (c : ℕ → ℝ) (C : ℝ) (n : ℕ)
    (hcoeff : ∀ p ∈ n.factorization.support, |c p| ≤ C * Real.log p) :
    |primeFactorResidual c n| ≤ C * Real.log n := by
  classical
  unfold primeFactorResidual
  calc
    |∑ p ∈ n.factorization.support, (n.factorization p : ℝ) * c p|
        ≤ ∑ p ∈ n.factorization.support,
            |(n.factorization p : ℝ) * c p| := Finset.abs_sum_le_sum_abs _ _
    _ = ∑ p ∈ n.factorization.support,
          (n.factorization p : ℝ) * |c p| := by
          apply Finset.sum_congr rfl
          intro p hp
          rw [abs_mul, abs_of_nonneg]
          positivity
    _ ≤ ∑ p ∈ n.factorization.support,
          (n.factorization p : ℝ) * (C * Real.log p) := by
          gcongr with p hp
          exact hcoeff p hp
    _ = C * Real.log n := by
          rw [Real.log_nat_eq_sum_factorization]
          simp only [Finsupp.sum]
          rw [Finset.mul_sum]
          apply Finset.sum_congr rfl
          intro p hp
          ring

/-- A centered finite prime coefficient family gives an exact mean-zero
prime-power perturbation and a logarithmically controlled divisor residual. -/
theorem finite_prime_factor_conditioning_construction
    (P : Finset ℕ) (q : ℕ) (raw : ℕ → ℝ) (C : ℝ)
    (hprime : ∀ p ∈ P, Nat.Prime p)
    (hqP : q ∈ P)
    (hnonzero : ∃ p ∈ P.erase q, raw p ≠ 0)
    (hC : 0 ≤ C)
    (hcoeff : ∀ p ∈ P,
      |centeredPrimeCoefficient P q raw p| ≤ C * Real.log p) :
    (∑ p ∈ P,
        centeredPrimeCoefficient P q raw p / ((p : ℝ) - 1) = 0) ∧
      (∀ n : ℕ,
        |primeFactorResidual (centeredPrimeCoefficient P q raw) n| ≤
          C * Real.log n) ∧
      ∃ p ∈ P,
        centeredPrimeCoefficient P q raw p ≠ 0 ∧
        primeFactorResidual (centeredPrimeCoefficient P q raw) p =
          centeredPrimeCoefficient P q raw p := by
  have hq : 1 < q := (hprime q hqP).one_lt
  refine ⟨centeredPrimeCoefficient_weighted_sum_zero P q raw hqP hq, ?_, ?_⟩
  · intro n
    apply primeFactorResidual_abs_le_log
    intro p hp
    by_cases hpP : p ∈ P
    · exact hcoeff p hpP
    · rw [centeredPrimeCoefficient_eq_zero_of_not_mem P q raw hpP, abs_zero]
      exact mul_nonneg hC (Real.log_nonneg (by
        exact_mod_cast (Nat.prime_of_mem_primeFactors hp).one_le))
  · rcases hnonzero with ⟨p, hpErase, hpRaw⟩
    have hpP : p ∈ P := Finset.mem_of_mem_erase hpErase
    have hpq : p ≠ q := (Finset.mem_erase.mp hpErase).1
    have hpCentered : centeredPrimeCoefficient P q raw p ≠ 0 := by
      rw [centeredPrimeCoefficient_eq_raw P q raw hpP hpq]
      exact hpRaw
    refine ⟨p, hpP, hpCentered, ?_⟩
    simp [primeFactorResidual, (hprime p hpP).factorization]

end RiemannHypothesisProofFactory.SelbergConditioning
