import RiemannHypothesisProofFactory.MobiusResidualComplexity.ResearchBarrierCertificate
import RiemannHypothesisProofFactory.MobiusResidualComplexity.PrimeBandAsymptotics
import RiemannHypothesisProofFactory.MobiusResidualComplexity.ThresholdAsymptotics

/-!
# Möbius residual-complexity certificate

The selected results prove the eventual fixed-band product population, the
finite global-matching obstruction, the exact logarithmic scale conversion,
and residual-budget separation along that scale.
-/

#print axioms RiemannHypothesisProofFactory.MobiusResidualComplexity.eventually_octuplePrimeBand_product_population
#print axioms RiemannHypothesisProofFactory.MobiusResidualComplexity.chebyshev_globalMatching_population_barrier
#print axioms RiemannHypothesisProofFactory.MobiusResidualComplexity.threshold_logarithmic_scale_conversion
#print axioms RiemannHypothesisProofFactory.MobiusResidualComplexity.eventually_threshold_budget_separation
