import RiemannHypothesisProofFactory.CriticalExponentTransforms.MixtureGapLaw
import RiemannHypothesisProofFactory.CriticalExponentTransforms.PhaseOrbit

/-!
# Critical-exponent transforms certificate

The main theorem derives the finite perturbation mixture from a multilinear
operator and its dilation covariance. It proves the first-visible norm and
dyadic-energy limits, positivity of the leading energy constant, and the
strict critical-exponent gap.
-/

#print axioms RiemannHypothesisProofFactory.CriticalExponentTransforms.multilinear_power_tuple_law
#print axioms RiemannHypothesisProofFactory.CriticalExponentTransforms.multilinear_operator_expansion
#print axioms RiemannHypothesisProofFactory.CriticalExponentTransforms.paper_multilinear_operator_expansion
#print axioms RiemannHypothesisProofFactory.CriticalExponentTransforms.multilinear_grouped_expansion
#print axioms RiemannHypothesisProofFactory.CriticalExponentTransforms.normalizedMixtureDyadicEnergy_tendsto
#print axioms RiemannHypothesisProofFactory.CriticalExponentTransforms.paper_normalized_mixture_dyadic_energy_limit
#print axioms RiemannHypothesisProofFactory.CriticalExponentTransforms.mixtureDyadicEnergyLeadingConstant_pos
#print axioms RiemannHypothesisProofFactory.CriticalExponentTransforms.scale_normalized_operator_profile_eq
#print axioms RiemannHypothesisProofFactory.CriticalExponentTransforms.multilinear_mixture_gap_law
#print axioms RiemannHypothesisProofFactory.CriticalExponentTransforms.phase_orbit_normal_form
#print axioms RiemannHypothesisProofFactory.CriticalExponentTransforms.log_dyadic_energy_reduction
#print axioms RiemannHypothesisProofFactory.CriticalExponentTransforms.phase_orbit_energy_recurrence
#print axioms RiemannHypothesisProofFactory.CriticalExponentTransforms.phase_orbit_full_turn_energy_law
